# Tipos de Amostragem

## Carregamento da base de dados - census

In [5]:
import random
import numpy as np
import pandas as pd
import math

In [36]:
df_census = pd.read_csv('J:/Udemy/Machine Learning/Estatística para Ciência de Dados e Machine Learning/projeto-estatistica-mlops/Bases de dados/census.csv')

In [3]:
"""
A base census foi criada a partir de uma amostra da Pesquisa da População Atual (Current Population Survey - CPS), 
e seu principal objetivo é prever se uma pessoa ganha mais de 50 mil dólares por ano,
com base em atributos demográficos e econômicos. Essa Amostra contém 32.560 registros.

+++++++++++++++++++++++ METADADOS +++++++++++++++++++++++
    | Coluna           | Descrição                                                                                           |
    | ---------------- | --------------------------------------------------------------------------------------------------- |
    | `age`            | Idade da pessoa (em anos).                                                                          |
    | `workclass`      | Tipo de classe trabalhista (por exemplo, setor privado, governo, etc.).                             |
    | `final-weight`   | Peso final atribuído ao indivíduo pela amostragem do censo (para análise estatística da população). |
    | `education`      | Nível educacional atingido (por exemplo, ensino médio, bacharelado, etc.).                          |
    | `education-num`  | Número correspondente ao nível de escolaridade (codificado numericamente).                          |
    | `marital-status` | Estado civil (solteiro, casado, divorciado, etc.).                                                  |
    | `occupation`     | Ocupação da pessoa (por exemplo, técnico, executivo, etc.).                                         |
    | `relationship`   | Relação da pessoa com outros residentes no domicílio (por exemplo, cônjuge, filho, etc.).           |
    | `race`           | Raça da pessoa (por exemplo, White, Black, Asian-Pac-Islander, etc.).                               |
    | `sex`            | Sexo da pessoa (Male ou Female).                                                                    |
    | `capital-gain`   | Ganhos de capital (valores acima de salários normais).                                              |
    | `capital-loos`   | Perdas de capital (valores negativos por investimentos ou bens).                                    |
    | `hour-per-week`  | Número de horas trabalhadas por semana.                                                             |
    | `native-country` | País de origem (ex: United States, Mexico, etc.).                                                   |
    | `income`         | Faixa de renda: `<=50K` (até 50 mil) ou `>50K` (acima de 50 mil dólares por ano).                   | 
"""

'\nA base census foi criada a partir de uma amostra da Pesquisa da População Atual (Current Population Survey - CPS), \ne seu principal objetivo é prever se uma pessoa ganha mais de 50 mil dólares por ano,\ncom base em atributos demográficos e econômicos. Essa Amostra contém 32.560 registros.\n\n+++++++++++++++++++++++ METADADOS +++++++++++++++++++++++\n    | Coluna           | Descrição                                                                                           |\n    | ---------------- | --------------------------------------------------------------------------------------------------- |\n    | `age`            | Idade da pessoa (em anos).                                                                          |\n    | `workclass`      | Tipo de classe trabalhista (por exemplo, setor privado, governo, etc.).                             |\n    | `final-weight`   | Peso final atribuído ao indivíduo pela amostragem do censo (para análise estatística da população). |\n    | `education`      | Nível educacional atingido (por exemplo, ensino médio, bacharelado, etc.).                          |\n    | `education-num`  | Número correspondente ao nível de escolaridade (codificado numericamente).                          |\n    | `marital-status` | Estado civil (solteiro, casado, divorciado, etc.).                                                  |\n    | `occupation`     | Ocupação da pessoa (por exemplo, técnico, executivo, etc.).                                         |\n    | `relationship`   | Relação da pessoa com outros residentes no domicílio (por exemplo, cônjuge, filho, etc.).           |\n    | `race`           | Raça da pessoa (por exemplo, White, Black, Asian-Pac-Islander, etc.).                               |\n    | `sex`            | Sexo da pessoa (Male ou Female).                                                                    |\n    | `capital-gain`   | Ganhos de capital (valores acima de salários normais).                                              |\n    | `capital-loos`   | Perdas de capital (valores negativos por investimentos ou bens).                                    |\n    | `hour-per-week`  | Número de horas trabalhadas por semana.                                                             |\n    | `native-country` | País de origem (ex: United States, Mexico, etc.).                                                   |\n    | `income`         | Faixa de renda: `<=50K` (até 50 mil) ou `>50K` (acima de 50 mil dólares por ano).                   | \n'

In [4]:
df_census.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
df_census.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Amostragem aleatória simples

In [6]:
# sample -> seleciona a quantidade de amostras de uma população
# random_state=N -> Cria um identificador para a sua amostra.
df_amostra_simples = df_census.sample(n = 100, random_state=1)

df_amostra_simples.shape

(100, 15)

In [7]:
df_amostra_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

In [8]:
# random_state -> Os resultados de amostragem serão os mesmos em outra máquina. Isso ocorre pois a base de dados é idêntica  possuindo os mesmos dados e padrão de escolha.

def amostra_aleatoria_simples(dataset: pd.DataFrame,
                              qtd_amostras: int,
                              id_amostra: int) -> pd.DataFrame:
    df = dataset.sample(n=qtd_amostras, random_state=id_amostra)
    return df

In [19]:
df_amostra_simples = amostra_aleatoria_simples(df_census, 28, 1)

In [20]:
df_amostra_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

## Amostragem sistemática

In [11]:
def amostra_sistematica(qtd_amostra, df):
    calculo = math.trunc(len(df) // qtd_amostra)
    random.seed(1)
    valor_inicial = random.randint(0, calculo)
    indices = np.arange(valor_inicial, len(df), step=calculo)

    amostra = df.iloc[indices]
    return amostra

In [12]:
amostra_sistematica(100, df_census)

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
68,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
393,34,State-gov,98101,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,45,?,>50K
718,22,Private,214399,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
1043,44,Private,167005,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,60,United-States,>50K
1368,52,Private,152234,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,99999,0,40,Japan,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30943,33,Private,48010,Some-college,10,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
31268,43,Private,306440,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,66,France,<=50K
31593,37,Private,171968,Assoc-voc,11,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
31918,26,Private,154571,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Male,0,0,45,United-States,>50K
32243,33,Private,198069,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,65,United-States,<=50K

## Amostragem por grupos

In [71]:
def amostragem_agrupamento(df, qtd_grupos):
    # df_copy = df.copy()
    qtd_registros = len(df) // qtd_grupos
    grupos = []
    id_grupo = 1
    contagem = 0
    # Itera sobre todas as linhas do df
    for _ in df.iterrows():
        grupos.append(id_grupo)
        contagem += 1
        if contagem > qtd_registros:
            contagem = 0
            id_grupo += 1

    # Cria a coluna grupos
    df['grupo'] = grupos

    random.seed(1)
    grupo_sort = random.randint(1,qtd_grupos)
    return df[df['grupo'] == grupo_sort]

In [72]:
amostra_grupo = amostragem_agrupamento(df_census, 325)

In [47]:
amostra_grupo.shape, amostra_grupo['grupo'].value_counts()

((101, 16),
 grupo
 69    101
 Name: count, dtype: int64)

In [29]:
# Valida o grupo sorteado e a quantidade
amostra_grupo['grupo'].value_counts()

grupo
69    101
Name: count, dtype: int64

In [30]:
amostra_grupo.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
6868,32,Private,128016,HS-grad,9,Married-spouse-absent,Other-service,Unmarried,White,Female,0,0,20,United-States,<=50K,69
6869,46,Private,360096,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,15024,0,60,United-States,>50K,69
6870,30,Private,170154,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Female,0,0,40,United-States,>50K,69
6871,35,Private,337286,Masters,14,Never-married,Exec-managerial,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K,69
6872,52,Private,204322,Assoc-voc,11,Married-civ-spouse,Tech-support,Husband,White,Male,5013,0,40,United-States,<=50K,69

In [200]:
# Valida a quantidade de registros por valor unico
# np.unique(grupos, return_counts=True)

## Amostragem estratificada

In [57]:
# Biblioteca que faz o calculo da amostra estratificada
from sklearn.model_selection import StratifiedShuffleSplit

In [ ]:
# Contando quantos registros temos para cada grupo de salario
df_census['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [ ]:
# Porcentagem de cada grupo de faixa salário na base inteira
7841 / len(df_census), 24720 / len(df_census)

(0.2408095574460244, 0.7591904425539756)

In [88]:
# Queremos 100 registros como amostra. Precisamos identificar esse valor em porcentagem
porcent = 100 / len(df_census)

In [ ]:
# StratifiedShuffleSplit -> Utilizada para buscar a quantidade de registros de uma base. É muito utilizado para treinar modelos de MLops
split = StratifiedShuffleSplit(test_size=porcent)
for x, y in split.split(df_census, df_census['income']):
    df_x = df_census.iloc[x]
    df_y = df_census.iloc[y]

In [ ]:
# Com essa validação, confirmaos que ele definiu proporcionalmente dos elementos em uma das celulas anteriores
df_y['income'].value_counts()

income
<=50K    76
>50K     24
Name: count, dtype: int64

In [89]:
df_y.head()
df_x.shape, df_y.shape

((32461, 16), (100, 16))